name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /root/entrepreneur-morocco-old
            git pull origin main
            npm ci
            npm run build
            pm2 delete entrepreneur-morocco || true
            PORT=3002 pm2 start npm --name "entrepreneur-morocco" -- start
            pm2 save
